MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN_PANET1_v2_2_v1.fpn_ResNet50_conv5_body
  FASTER_RCNN: True
  MASK_ON: True
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet50_caffe.pth'
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.02
  GAMMA: 0.1
  MAX_ITER: 40000
  STEPS: [0, 44000, 48000]
FPN:
  FPN_ON: True
  PANET_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads_panet2_v1.roi_Xconv1fc_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
MRCNN:
  ROI_MASK_HEAD: mask_rcnn_heads_panet23_v1.mask_rcnn_fcn_head_v1up4convs
  RESOLUTION: 56  # (output mask resolution) default 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 28  # default 7
  ROI_XFORM_SAMPLING_RATIO: 2  # default 0
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default GaussianFill
TRAIN:
  SCALES: (800,)
  MAX_SIZE: 3000
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  SCALE: 800
  MAX_SIZE: 3000
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  SOFT_NMS:
        ENABLED: False
  BBOX_VOTE:
        ENABLED: False
  BBOX_AUG:
        ENABLED: False
        SCORE_HEUR: UNION
        COORD_HEUR: UNION
        H_FLIP: True
        SCALES: (1800,2000,2200,2400)
        MAX_SIZE: 3600
        SCALE_H_FLIP: True
        SCALE_SIZE_DEP: False
        AREA_TH_LO: 2500
        AREA_TH_HI: 32400
        ASPECT_RATIOS: ()
        ASPECT_RATIO_H_FLIP: False
  MASK_AUG:
        ENABLED: False
        HEUR: SOFT_AVG
        H_FLIP: True
        SCALES: (800, 1000, 1200, 1400, 1800, 2000, 2200, 2400)
        MAX_SIZE: 3600
        SCALE_H_FLIP: True
        SCALE_SIZE_DEP: False
        AREA_TH: 32400
        ASPECT_RATIOS: ()
        ASPECT_RATIO_H_FLIP: False
